---
collections:
  - name: community.crypto
    version: 3.3.0
  - name: community.general
    version: 10.7.9
  - name: ansible.posix
    version: 2.2.2
  - name: kubernetes.core
    version: 6.5.0
  - name: community.docker
    version: 5.2.1
  - name: community.vmware
    version: 6.2.0
  - name: awx.awx
    version: 24.6.1
  - name: community.hashi_vault
    version: 7.1.0
  - name: ansible.netcommon
    version: 8.6.0

roles:
  - src: https://github.com/stuttgart-things/install-requirements.git
    scm: git
