---
- name: "Check if file {{ item.value.bin_dir }}/{{ item.value.bin_name }} exists"
  stat:
    path: "{{ item.value.bin_dir }}/{{ item.value.bin_name }}"
  register: status_file_exists

- name: "Calculate MD5 Checksum from file {{ item.value.bin_dir }}/{{ item.value.bin_name }}"
  stat:
    path: "{{ item.value.bin_dir }}/{{ item.value.bin_name }}"
  register: status_checksum
  when: status_file_exists.stat.exists

- name: Output checksum
  debug:
    msg: "File: {{ item.value.bin_dir }}/{{ item.value.bin_name }} has MD5 checksum: {{ status_checksum }}"
  when: status_file_exists.stat.exists

- name: Check if checksum is correct 
  set_fact: 
    checksum_wrong: true
  when: md5_checksum != status_checksum and status_file_exists.stat.exists