---
- name: "Calculate MD5 Checksum from file {{ item.value.bin_dir }}/{{ item.value.bin_name }}"
  stat:
    path: "{{ item.value.bin_dir }}/{{ item.value.bin_name }}"
    checksum_algorithm: md5
  register: status_checksum

- name: Output checksum
  debug:
    msg: "File: {{ item.value.bin_dir }}/{{ item.value.bin_name }} has MD5 checksum: {{ status_checksum.stat.md5 }} expected MD5: {{ item.value.md5_checksum }}"
  when: status_checksum.stat.exists | bool

- name: Checksum verify
  block:
    - name: Check if checksum is correct 
      set_fact: 
        checksum_wrong: true
      when: (item.value.md5_checksum != status_checksum.stat.checksum )
  when: status_checksum.stat.exists | bool