---
- name: "Which {{ item.value.bin_name }}"
  ansible.builtin.command: "which {{ item.value.bin_name }}"
  register: res_path
  changed_when: false
  failed_when: false

- name: "Is the package {{ item.value.bin_name }} installed?"
  ansible.builtin.set_fact:
    is_installed: "{{ res_path.stdout | length > 0 }}"

- name: "Is {{ item.value.bin_name }} installed at {{ install_path }}?"
  ansible.builtin.set_fact:
    is_in_bin_dir: "{{ res_path.stdout == install_path }}"
