---
- name: Check installed version of {{ item.value.bin_name }}
  ansible.builtin.command: "{{ item.value.bin_name }} {{ item.value.version_cmd }}"
  register: result_c
  changed_when: false
  failed_when: false

- name: Compare installed version and wanted version
  ansible.builtin.set_fact:
    versions_match: "{{ item.value.bin_version in result_c.stdout }}"
