---
- name: Create temporary download directory (if it does not exist)
  file:
    path: "{{ download_dir }}"
    state: directory
    mode: '1777'

- name: download -- {{ item.value.bin_name }}
  get_url:
    ulr: "{{ item.value.source_url }}"
    dest: "{{ download_dir }}"
    validate_certs: no
  when: "'zip' or 'tar' not in item.value.source_url"
  tags: download

- name: download and unarchive -- {{ item.value.bin_name }}
  unarchive:
    src: "{{ item.value.source_url }}"
    dest: "{{ download_dir }}"
    validate_certs: no
    remote_src: yes
  when: "'zip' or 'tar' in item.value.source_url"
  tags: download

- name: copy binary -- {{ item.value.bin_name }}
  copy:
    src: "{{ download_dir }}/{{ item.value.bin_to_copy }}"
    dest: "{{ item.value.bin_dir }}"
    mode: 0755
    remote_src: yes

- name: delete downloading dir -- {{ item.value.bin_name }}
  file:
    path: "{{ download_dir }}/{{ item.value.to_remove }}"
    state: absent
