---
- name: Include checksum tasks
  ansible.builtin.include_tasks: compare-checksum.yaml
  when: item.value.md5_checksum is defined

- name: Include installation check tasks
  ansible.builtin.include_tasks: check-installation.yaml

- name: Include tasks for deleting binarys
  ansible.builtin.include_tasks: delete-binary.yaml
  when: is_in_bin_dir and ( wanted_state =="absent" ) or checksum_wrong | bool

- name: Include binary check tasks
  ansible.builtin.include_tasks: check-binary-version.yaml
  when: ( wanted_state=="present" ) and is_installed and is_in_bin_dir and
        ( item.value.check_bin_version_before_installing|bool ) and not checksum_wrong

- name: Include download tasks
  ansible.builtin.include_tasks: download-copy-binary.yaml
  when: ( wanted_state=="present" ) and
        ( (versions_match is not defined) or (not versions_match) ) or checksum_wrong | bool
