---
- name: Create temporary download directory (if it does not exist)
  file:
    path: /tmp/downloads
    state: directory

- name: download and unarchive -- {{ item.key }}
  unarchive:
    src: "{{ item.value.source_link }}"
    dest: /tmp/downloads
    copy: no
    validate_certs: no
    remote_src: yes
  tags: download

- name: copy binary -- {{ item.key }}
  copy:
    src: "{{ item.value.dir_to_copy }}"
    dest: "{{ item.value.bin_dir }}"
    mode: 0755
    remote_src: yes

- name: delete downloading dir -- {{ item.key }}
  file:
    path: "{{ item.value.dir_to_delete }}"
    state: absent
