---
- include: check-installation.yml

- include: delete-bin.yml
  when: is_in_bin_dir and ( wanted_state =="absent" ) or md5_checksum != status_checksum

- include: check-bin-version.yml
  when: ( wanted_state=="present" ) and is_installed and is_in_bin_dir and 
        ( item.value.check_bin_version_before_installing|bool )
        
- include: dl_cp_binary.yml
  when: ( wanted_state=="present" ) and 
        ( (versions_match is not defined) or (not versions_match) ) or md5_checksum != status_checksum
