---
- include: check-installation.yml

- include: check-bin-version.yml
  when: is_installed and 
        ( item.value.check_bin_version_before_installing|bool )

- include: dl_cp_binary.yml
  when: (versions_match is not defined) or (not versions_match)