---
name: Run Molecule tests
on:
  workflow_dispatch:

jobs:
  molecule:
    runs-on: docker-group
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        with:
          path: "${{ github.repository }}"

      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_args: --scenario-name ${{ matrix.scenario }}
        env:
          ANSIBLE_FORCE_COLOR: '1'