---
name: Release Ansible Module
on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: release-tag
        required: true
        type: string
      release-message:
        description: release-message
        required: true
        type: string

jobs:
  release-ansible:
    name: Release
    uses: stuttgart-things/github-workflow-templates/.github/workflows/call-release-module.yaml@feature/add-homerun-task-go # ansible-lint-24.2.1
    with:
      module-name: install-configure-docker
      tag-name: "${{ github.event.inputs.release-tag }}"
      release-message: "${{ github.event.inputs.release-message }}"
      environment-name: k8s
      archive-kind: tar.gz
      runs-on: ghr-install-configure-docker-skyami-cicd
      continue-error: false