---
name: Release Ansible Module
on:
  workflow_dispatch:
    inputs:
      release-tag:
        required: true
        type: string
      release-message:
        required: true
        type: string

jobs:
  release-ansible:
    name: Release
    uses: stuttgart-things/stuttgart-things/.github/workflows/release-module.yaml@main
    with:
      module-name: download-install-binary
      tag-name: "${{ github.event.inputs.release-tag }}"
      release-message: "${{ github.event.inputs.release-message }}"
      environment-name: k8s
      archive-kind: tar.gz
      runs-on: ghr-download-install-binary-labda-test
      continue-error: false
