---
name: Validate and Release Ansible Module
on:
  workflow_dispatch:
    inputs:
      release-tag:
        required: true
        type: string
      release-message:
        required: true
        type: string

jobs:
  release-ansible:
    name: Release
    uses: stuttgart-things/stuttgart-things/.github/workflows/release-terraform.yaml@main  
    with:
      module-name: ghr-download-install-binary-cicd
      tag-name: "${{ github.event.inputs.release-tag }}"
      release-message: "${{ github.event.inputs.release-message }}"
      environment-name: k8s
      runs-on: ghr-s3-minio-config-sthings-cicd
      continue-error: false
