---
name: Ansible lint
on:
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches:
      - 'main'
      - 'feature/**'
      - 'fix/**'
  workflow_dispatch:

jobs:
  yaml-lint:
    name: Lint yaml files
    uses: stuttgart-things/github-workflow-templates/.github/workflows/call-yaml-lint.yaml@feature/add-homerun-task-go
    with:
      runs-on: ghr-download-install-binary-skyami-cicd
      environment-name: k8s
      continue-error: true
      yamllint-version: 1
      lintprofile-path: .yamllint
      artifact-name: yaml-lint

  ansible-lint:
    name: Lint ansible code
    uses: stuttgart-things/github-workflow-templates/.github/workflows/call-ansible-lint.yaml@feature/add-homerun-task-go # ansible-lint-24.2.1
    with:
      runs-on: ghr-download-install-binary-skyami-cicd
      environment-name: k8s
      continue-error: true
      ansible-image: eu.gcr.io/stuttgart-things/sthings-ansible:10.3.0
      playbook: tests/test.yml
    needs: yaml-lint

  molecule-test:
    name: Test ansible code w/ molecule
    uses: stuttgart-things/github-workflow-templates/.github/workflows/call-moluecule-test.yaml@feature/add-homerun-task-go # ansible-lint-24.2.1
    with:
      runs-on: dagger
      environment-name: k8s
      scenario-names: "['default']"
    # needs: ansible-lint
